name: rag-chatbot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit==1.35.0
      - langchain
      - langchain-community
      - openai
      - faiss-cpu
      - python-dotenv
      - PyPDF2
      - protobuf==3.20.3